### ISSUE TITLE
Provide easy way to output licenses

### ISSUE THREAD

**Issue by xavez** [mono-company/bedrock#107]
@thomastuts already wrote some code, based on the [license checker](https://github.com/davglass/license-checker) npm package:

```
const licenses = require('./licenses.json');

const uniqueLicenses = [];

for (const moduleName in licenses) {
  const licenseInfo = licenses[moduleName];
  if (!uniqueLicenses.includes(licenseInfo.licenses)) {
    uniqueLicenses.push(licenseInfo.licenses);
  }
}

console.log(JSON.stringify(uniqueLicenses, null, 2));
```

Ideally, we can make a separation between modules used as dependencies an those used as devDependencies.

**Comment by Wolfr** [comment]
Why does this matter?

**Comment by xavez** [comment]
It matters because if you make software, you want to make sure the licenses that are used are in line with your business model and your own licenses. It’s software 101.

Why wouldn’t it matter?

**Comment by Wolfr** [comment]
Because this is the Bedrock repo and Bedrock is used to create prototypes.

I don't want to litter Bedrock with edge case features. Checking your licenses is a separate thing.

**Comment by Wolfr** [comment]
Don't get me wrong, this is definitely important, but not here.

**Comment by xavez** [comment]
I disagree, and this needs to be a conversation.

**Comment by Wolfr** [comment]
I agree it needs to be a conversation but this space specifically is for issues with Bedrock. I don't want it to be the place for discussions about what Bedrock should be.

I need to be able to see which **very concrete** actions I can take them to improve Bedrock by looking at the issues list. That's why I closed the issue. Not because I don't want to have a conversation, but because this is not the place to have it.
