### ISSUE TITLE
Copy to clipboard: improve the way this works

### ISSUE THREAD

**Issue by xavez** [mono-company/bedrock#108]
In the styleguide, copy to clipboard does not work in every browser. My guess is because of security preferences / implementation.

What we could do is add a shortcut to select all the text, so that a user can hit <kbd>cmd+c</kbd> easily

**Comment by Wolfr** [comment]
I checked the docs and the 1 browser that is not supported is Safari, see the relevant [npm](https://www.npmjs.com/package/clipboard) module.

I fixed a few things in ec1c4afea54aeb87144e72599fe7804075a27b9e to improve copy/pasting of code,

One thing I fixed was a bug where the code would get cut off:
http://cl.ly/2i2M3n422y3q/Screen%20Shot%202016-07-05%20at%2015.02.00.png

Another thing I changed is the behavior: the copy button only shows up when you are hovering over the code (therefore you can hover outside to not obscure the code).

Next to this I stopped the button from showing up in Safari, because it's not supported there. I used an ugly hack.

We could go further and improve upon this by implementing what is described on https://clipboardjs.com/ but I don't have the necessary JS-fu for that (cc @thomastuts ).

**Comment by Wolfr** [comment]
Copy to clipboard is now supported in Safari on Sierra so we should investigate this again.

**Comment by Wolfr** [comment]
I removed the hack. This fixes the original issue.
