### ISSUE TITLE
Current Bedrock does not actually compile properly to dist folder

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#116]
There is no correct output to the the dist folder at the moment. I think this is related to the changes in #85 .

Steps to reproduce:

* Check out latest Bedrock
* Look at the templates: there is 1 folder called `about` that has an `index.jade` file
Run `gulp build`
* Look at the results in dist: there is no CSS, and no templates other than templates at the root level `404` and `index` and the templates from the styleguide. The other templates are missing.

Is this causing the error?
https://github.com/mono-company/bedrock/blob/master/core/tasks/templates.js#L113

If possible please check this fast, we need to show new prototypes to our clients soon :)

**Comment by thomastuts** [comment]
I added a fix in https://github.com/mono-company/bedrock/commit/9f1eb8d8950e24766f75d34e0d1b67d07d41f617. Can you try that out and see if it works? Looks fine on my end now. The downside to this is that `modules/` no longer gets treated as a special folder, so it'll show up in the page tree:

![image](https://cloud.githubusercontent.com/assets/1914255/19548908/7781909c-96a1-11e6-94e2-3b970ac736cb.png)

But since you can now use an arbitrary directory structure, maybe putting stuff in `modules/` isn't even needed anymore?
