### ISSUE TITLE
Icon font only compiles when you make a change in the icon-font-source directory

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#118]
1. Check out Bedrock
2. Delete `icon-font-tmp` if it exists
3. Delete `compiled` folder
4. Run `gulp`. Go to the styleguide and look at the docs. The icon font will be broken.
5. Now copy a new icon in `icon-font-source`. The icon font will regenerate and work.

**Comment by xavez** [comment]
To fix this, the compile task needs to run at least once on `gulp watch` I think?

**Comment by Wolfr** [comment]
The default task is `gulp` not `gulp watch`:

    gulp.task('default', ['browser-sync']);

This task runs browser-sync, which runs this:

    gulp.task('browser-sync', ['server', 'compile-all', 'watch'], browserSync);

The 2nd task here is compile-all which runs the icon font:

    gulp.task('compile-all', ['modernizr', 'icon-font', 'bundle', 'sass', 'copy']);

So it actually runs, but it doesn't do what it's supposed to do. It seems that browsersync triggers the actual task.

**Comment by thomastuts** [comment]
The icon font only compiles if it detects any changes. If you only remove the `compiled/` and `icon-font-tmp/` folders, it'll still think nothing has changed because you didn't remove the `.fontcustom-manifest.json` file.

Can you describe a use case where this actually happens? On first project start (ever), it'll create all necessary files and create the icon font properly, and then it will do so again when any icons have changed. I don't really see why there's a need to remove the `icon-font-tmp/` folder?

**Comment by Wolfr** [comment]
Oops. Not very clear. This occured while merging an old Bedrock into a new one. I'll put this on hold and close it if it doesn't occur anymore.
