### ISSUE TITLE
The prototype navigation "remember" functionality fails when there are many templates

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#121]
In one of our projects we have a lot of templates (over 60); in this case the "remember" functionality fails.

> Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'bedrock.prototypeNavState' exceeded the quota.(…)

![screen shot 2016-11-18 at 11 20 18](https://cloud.githubusercontent.com/assets/12690/20426812/2039fb0c-ad81-11e6-878a-060f64cc4fe7.png)

**Comment by Wolfr** [comment]
Update: I threw almost all templates out of the project to try and resolve the problem, but it doesn't help. 

![screen shot 2016-11-18 at 14 32 11](https://cloud.githubusercontent.com/assets/12690/20431711/d43a868e-ad9b-11e6-8764-857183fec844.png)

**Comment by Wolfr** [comment]
I cleared my local storage which contained an old similar item from another project I opened (Gearjot). I think this was causing the problem.

**Comment by thomastuts** [comment]
From what I can tell, this might continue to be an issue unless we change the code responsible for remembering this stuff.

The way it's coded right now is that the closed modules are saved in the same local storage key across all projects (because the domain (localhost)  and the key are always the same). This can result in extremely long arrays that try to save to local storage, which is what happened here.

I don't really think it's an issue worth pursuing right now since this only happens with people using Bedrock extensively, i.e. Mono. It's easily fixed by clearing local storage like you did, as long as you know the cause. It *can* be fixed, but this seems like something we can bundle into a next Bedrock update (eventually), rather than fixing it now.
