### ISSUE TITLE
Is it not possible to -not- have documentation

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#84]
If the documentation folder doesn't exist, you get an error.

http://cl.ly/1n1F2C2O2N3J/Screen%20Shot%202016-01-20%20at%2019.37.09.png

**Comment by thomastuts** [comment]
This seems to work for me without any code changes, can you try to reproduce it please? When removing all docs in the folder and/or the docs folder itself, I don't get any errors.

**Comment by Wolfr** [comment]
Just reproduced within DeskDrive
http://cl.ly/462x1w3y3t2M/ScreenFlow.mp4

**Comment by thomastuts** [comment]
You seem to be getting that error because you are still trying to request a file (the introduction documentation) that does not exist through its URL. Changing your URL to a working link should fix it. So it looks like the docs _can_ be fully removed, they just need a 404 handler instead of throwing a Jade error.

**Comment by Wolfr** [comment]
This remains an issue. I can't seem to build without a `docs` folder, and if I remove the `docs` folder or all documents in it it throws the error as reported.

Let's go through this in a Skype when we can to debug.

**Comment by Wolfr** [comment]
New info: when I delete a pattern, I run into the same error.
http://cl.ly/2G1X1r2U1V46/Screen%20Shot%202016-01-26%20at%2015.22.09.png

**Comment by Wolfr** [comment]
Silly me.
